server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /dachser {
        return 301 /dachser/;
    }

    location /dachser/ {
        try_files $uri $uri/ /dachser/index.html;
    }
}
