server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location = /dachserboard {
        return 301 /dachserboard/;
    }

    location /dachserboard/ {
        try_files $uri $uri/ /dachserboard/index.html;
    }
}
